[package]
name = "zephyr"
version = "0.1.0"
edition = "2021"

[dependencies]
zephyr-lexer = { path = "../zephyr-lexer" }
zephyr-parser = { path = "../zephyr-parser" }
zephyr-span = { path = "../zephyr-span" }
zephyr-tycheck = { path = "../zephyr-tycheck" }
